export const EMERALD_EVENT_FLAGS_BASE_OFFSET = 0x1270;
export const FRLG_EVENT_FLAGS_BASE_OFFSET = 0x0ee0;

// Emerald Move Tutor Flag IDs
export const EMERALD_MOVE_TUTOR_SWAGGER_FLAG = 433; // 0x1B1
export const EMERALD_MOVE_TUTOR_ROLLOUT_FLAG = 434; // 0x1B2
export const EMERALD_MOVE_TUTOR_FURY_CUTTER_FLAG = 435; // 0x1B3
export const EMERALD_MOVE_TUTOR_MIMIC_FLAG = 436; // 0x1B4
export const EMERALD_MOVE_TUTOR_METRONOME_FLAG = 437; // 0x1B5
export const EMERALD_MOVE_TUTOR_SLEEP_TALK_FLAG = 438; // 0x1B6
export const EMERALD_MOVE_TUTOR_SUBSTITUTE_FLAG = 439; // 0x1B7
export const EMERALD_MOVE_TUTOR_DYNAMIC_PUNCH_FLAG = 440; // 0x1B8
export const EMERALD_MOVE_TUTOR_DOUBLE_EDGE_FLAG = 441; // 0x1B9
export const EMERALD_MOVE_TUTOR_EXPLOSION_FLAG = 442; // 0x1BA

// FireRed/LeafGreen Move Tutor Flag IDs
export const FRLG_MOVE_TUTOR_DOUBLE_EDGE_FLAG = 704; // 0x2C0
export const FRLG_MOVE_TUTOR_THUNDER_WAVE_FLAG = 705; // 0x2C1
export const FRLG_MOVE_TUTOR_ROCK_SLIDE_FLAG = 706; // 0x2C2
export const FRLG_MOVE_TUTOR_EXPLOSION_FLAG = 707; // 0x2C3
export const FRLG_MOVE_TUTOR_MEGA_PUNCH_FLAG = 708; // 0x2C4
export const FRLG_MOVE_TUTOR_MEGA_KICK_FLAG = 709; // 0x2C5
export const FRLG_MOVE_TUTOR_DREAM_EATER_FLAG = 710; // 0x2C6
export const FRLG_MOVE_TUTOR_SOFT_BOILED_FLAG = 711; // 0x2C7
export const FRLG_MOVE_TUTOR_SUBSTITUTE_FLAG = 712; // 0x2C8
export const FRLG_MOVE_TUTOR_SWORDS_DANCE_FLAG = 713; // 0x2C9
export const FRLG_MOVE_TUTOR_SEISMIC_TOSS_FLAG = 714; // 0x2CA
export const FRLG_MOVE_TUTOR_COUNTER_FLAG = 715; // 0x2CB
export const FRLG_MOVE_TUTOR_METRONOME_FLAG = 716; // 0x2CC
export const FRLG_MOVE_TUTOR_MIMIC_FLAG = 717; // 0x2CD
export const FRLG_MOVE_TUTOR_BODY_SLAM_FLAG = 718; // 0x2CE
export const FRLG_MOVE_TUTOR_FRENZY_PLANT_FLAG = 734; // 0x2DE
export const FRLG_MOVE_TUTOR_BLAST_BURN_FLAG = 735; // 0x2DF
export const FRLG_MOVE_TUTOR_HYDRO_CANNON_FLAG = 736; // 0x2E0
export const BITS_PER_BYTE = 8;
