// RSE Flags
export const RSE_SYSTEM_FLAGS_START = 0x860;
export const RSE_FLAG_RECEIVED_MASTER_BALL = RSE_SYSTEM_FLAGS_START + 0x2a; // 0x88A - Using approximated offsets for major items
export const RSE_FLAG_DEFEATED_KYOGRE = RSE_SYSTEM_FLAGS_START + 0x2b;
export const RSE_FLAG_DEFEATED_GROUDON = RSE_SYSTEM_FLAGS_START + 0x2c;
export const RSE_FLAG_DEFEATED_RAYQUAZA = RSE_SYSTEM_FLAGS_START + 0x2d;

// FRLG Flags
export const FRLG_SYS_FLAGS_START = 0x800;
export const FRLG_FLAG_RECEIVED_MASTER_BALL = FRLG_SYS_FLAGS_START + 0x28; // 0x828
export const FRLG_FLAG_DEFEATED_MEWTWO = FRLG_SYS_FLAGS_START + 0x29;
export const FRLG_FLAG_DEFEATED_ZAPDOS = FRLG_SYS_FLAGS_START + 0x2a;
export const FRLG_FLAG_DEFEATED_MOLTRES = FRLG_SYS_FLAGS_START + 0x2b;
export const FRLG_FLAG_DEFEATED_ARTICUNO = FRLG_SYS_FLAGS_START + 0x2c;
