export const CONDITION_COOL_OFFSET = 0x06;
export const CONDITION_BEAUTY_OFFSET = 0x07;
export const CONDITION_CUTE_OFFSET = 0x08;
export const CONDITION_SMART_OFFSET = 0x09;
export const CONDITION_TOUGH_OFFSET = 0x0a;
export const CONDITION_SHEEN_OFFSET = 0x0b;
