packages:
  - "."
  - ".github/scripts"

legacyPeerDeps: true

minimumReleaseAgeExclude:
  - "@oxlint-tsgolint/*"
  - "oxlint-tsgolint"
  - "serialize-javascript"

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  msgpackr-extract: true
  workerd: true
  '@google/genai': set this to true or false
  protobufjs: set this to true or false

auditConfig:
  ignoreGhsas:
    - GHSA-rmmr-r34h-pfm5
