packages:
  - "."
  - ".github/scripts"

minimumReleaseAgeExclude:
  - "@oxlint-tsgolint/*"
  - "oxlint-tsgolint"
  - "serialize-javascript"

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  msgpackr-extract: true
  workerd: true
  '@google/genai': true
  protobufjs: true

auditConfig:
  ignoreGhsas:
    - GHSA-rmmr-r34h-pfm5
