// Module-level constants for bitmasks and RNG mechanics
export const RNG_50_PERCENT_MASK = 0b01111111;
export const RNG_50_PERCENT_THRESHOLD = 64;

/**
 * Timer Evaluation State
 */
export interface TimerState {
  delayMinsRemaining: number;
  timeCyclesSinceLastCall: number;
}

/**
 * Contact interface
 */
export interface Contact {
  id: number;
  name: string;
  isSwarm?: boolean;
  hasRareItem?: boolean;
  isHighValue?: boolean;
}

export const SWARM_FLAG_DUNSPARCE_BIT = 2;
export const SWARM_FLAG_YANMA_BIT = 3;

export const ITEM_FLAG_BEVERLY_BIT = 0;
export const ITEM_FLAG_JOSE_BIT = 1;
export const ITEM_FLAG_WADE_BIT = 2;
export const ITEM_FLAG_GINA_BIT = 3;
export const ITEM_FLAG_ALAN_BIT = 4;
export const ITEM_FLAG_LIZ_BIT = 5;
export const ITEM_FLAG_DEREK_BIT = 6;
export const ITEM_FLAG_TULLY_BIT = 7;
export const ITEM_FLAG_TIFFANY_BIT = 8;
export const ITEM_FLAG_WILTON_BIT = 9;

export const PHONE_CONTACT_BEVERLY = 6;
export const PHONE_CONTACT_JOSE = 13;
export const PHONE_CONTACT_WADE = 16;
export const PHONE_CONTACT_LIZ = 18;
export const PHONE_CONTACT_ANTHONY = 19;
export const PHONE_CONTACT_GINA = 21;
export const PHONE_CONTACT_ARNIE = 23;
export const PHONE_CONTACT_ALAN = 24;
export const PHONE_CONTACT_DEREK = 28;
export const PHONE_CONTACT_TULLY = 29;
export const PHONE_CONTACT_TIFFANY = 31;
export const PHONE_CONTACT_WILTON = 33;

/**
 * Checks if a phone call should trigger based on timer evaluation and a 50% RNG probability.
 *
 * Gen 2 RNG Call Trigger Logic:
 * 1. Timer Evaluation (`CheckReceiveCallTimer`): Compares delay times. If delay remains, no call.
 * 2. RNG Check (`CheckPhoneCall`): If timer checks pass, RNG is `and %01111111`.
 *    If the resulting number is odd/even or simply treated as 50% chance in logic (typically checked against half the mask space).
 *    In Gen 2 asm, `and %01111111` gives a number 0-127. Then it usually checks against half or another RNG value.
 *    Actually, wait, Gen 2 check is:
 *    call Random
 *    and %01111111
 *    cp <something>? Or just if (random & 0x7F) < 64? Wait, standard "50% chance" in Gen 2 is often `and %01111111`?
 *    The document says: "There is a 50% chance the call check proceeds."
 *    We can simulate this by taking a random byte and checking if `(randomByte & RNG_50_PERCENT_MASK) < 64`.
 *    Wait, `(randomByte & 0x7F) == 0` or similar? Let's just implement a pure 50% chance using the bitmask.
 *
 * @param timerState State representing the cooling-off period.
 * @param randomByte A random byte generated by the RNG (0-255).
 * @returns true if the phone call check passes, false otherwise.
 */
export function checkPhoneCall(timerState: TimerState, randomByte: number): boolean {
  // If we have mins remaining for delay, no call.
  if (timerState.delayMinsRemaining > 0) {
    return false;
  }

  // Apply the bitmask: and %01111111
  const maskedRng = randomByte & RNG_50_PERCENT_MASK;

  // 50% chance on a 0-127 range means checking if it's < 64.
  // This accurately reflects a 50% chance after the 0x7F mask.
  return maskedRng < RNG_50_PERCENT_THRESHOLD;
}

/**
 * Chooses a random caller uniformly from a pool of available callers.
 *
 * Gen 2 Caller Sampling (`ChooseRandomCaller`):
 * Uses `Random` along with `SimpleDivide` against `wNumAvailableCallers` to sample uniformly.
 *
 * @param availableCallers Array of contacts available at the current time.
 * @param randomByte A random byte generated by the RNG (0-255).
 * @returns The selected Contact, or null if no callers are available.
 */
export function chooseRandomCaller(availableCallers: Contact[], randomByte: number): Contact | null {
  if (!availableCallers || availableCallers.length === 0) {
    return null;
  }

  const numAvailable = availableCallers.length;

  // Gen 2 uses SimpleDivide, which is equivalent to modulo for picking an index.
  // randomByte % numAvailable
  const selectedIndex = randomByte % numAvailable;

  return availableCallers[selectedIndex] ?? null;
}

export function enrichContact(contact: Contact, swarmFlags: number, dailyItemFlags: number): Contact {
  let isSwarm = false;
  let hasRareItem = false;

  if (contact.id === PHONE_CONTACT_ANTHONY) {
    isSwarm = (swarmFlags & (1 << SWARM_FLAG_DUNSPARCE_BIT)) !== 0;
  } else if (contact.id === PHONE_CONTACT_ARNIE) {
    isSwarm = (swarmFlags & (1 << SWARM_FLAG_YANMA_BIT)) !== 0;
  }

  const checkItemFlag = (bit: number) => (dailyItemFlags & (1 << bit)) !== 0;

  switch (contact.id) {
    case PHONE_CONTACT_BEVERLY:
      hasRareItem = checkItemFlag(ITEM_FLAG_BEVERLY_BIT);
      break;
    case PHONE_CONTACT_JOSE:
      hasRareItem = checkItemFlag(ITEM_FLAG_JOSE_BIT);
      break;
    case PHONE_CONTACT_WADE:
      hasRareItem = checkItemFlag(ITEM_FLAG_WADE_BIT);
      break;
    case PHONE_CONTACT_GINA:
      hasRareItem = checkItemFlag(ITEM_FLAG_GINA_BIT);
      break;
    case PHONE_CONTACT_ALAN:
      hasRareItem = checkItemFlag(ITEM_FLAG_ALAN_BIT);
      break;
    case PHONE_CONTACT_LIZ:
      hasRareItem = checkItemFlag(ITEM_FLAG_LIZ_BIT);
      break;
    case PHONE_CONTACT_DEREK:
      hasRareItem = checkItemFlag(ITEM_FLAG_DEREK_BIT);
      break;
    case PHONE_CONTACT_TULLY:
      hasRareItem = checkItemFlag(ITEM_FLAG_TULLY_BIT);
      break;
    case PHONE_CONTACT_TIFFANY:
      hasRareItem = checkItemFlag(ITEM_FLAG_TIFFANY_BIT);
      break;
    case PHONE_CONTACT_WILTON:
      hasRareItem = checkItemFlag(ITEM_FLAG_WILTON_BIT);
      break;
  }

  const isHighValue = isSwarm || hasRareItem;

  return { ...contact, isSwarm, hasRareItem, isHighValue };
}

export function filterHighValueCalls(contacts: Contact[], swarmFlags: number, dailyItemFlags: number): Contact[] {
  return contacts.map((c) => enrichContact(c, swarmFlags, dailyItemFlags)).filter((c) => c.isHighValue);
}
