// Module-level constants for bitmasks and RNG mechanics
export const RNG_50_PERCENT_MASK = 0b01111111;
export const RNG_50_PERCENT_THRESHOLD = 64;

/**
 * Timer Evaluation State
 */
export interface TimerState {
  delayMinsRemaining: number;
  timeCyclesSinceLastCall: number;
}

/**
 * Contact interface
 */
export interface Contact {
  id: number;
  name: string;
}

/**
 * Checks if a phone call should trigger based on timer evaluation and a 50% RNG probability.
 *
 * Gen 2 RNG Call Trigger Logic:
 * 1. Timer Evaluation (`CheckReceiveCallTimer`): Compares delay times. If delay remains, no call.
 * 2. RNG Check (`CheckPhoneCall`): If timer checks pass, RNG is `and %01111111`.
 *    If the resulting number is odd/even or simply treated as 50% chance in logic (typically checked against half the mask space).
 *    In Gen 2 asm, `and %01111111` gives a number 0-127. Then it usually checks against half or another RNG value.
 *    Actually, wait, Gen 2 check is:
 *    call Random
 *    and %01111111
 *    cp <something>? Or just if (random & 0x7F) < 64? Wait, standard "50% chance" in Gen 2 is often `and %01111111`?
 *    The document says: "There is a 50% chance the call check proceeds."
 *    We can simulate this by taking a random byte and checking if `(randomByte & RNG_50_PERCENT_MASK) < 64`.
 *    Wait, `(randomByte & 0x7F) == 0` or similar? Let's just implement a pure 50% chance using the bitmask.
 *
 * @param timerState State representing the cooling-off period.
 * @param randomByte A random byte generated by the RNG (0-255).
 * @returns true if the phone call check passes, false otherwise.
 */
export function checkPhoneCall(timerState: TimerState, randomByte: number): boolean {
  // If we have mins remaining for delay, no call.
  if (timerState.delayMinsRemaining > 0) {
    return false;
  }

  // Apply the bitmask: and %01111111
  const maskedRng = randomByte & RNG_50_PERCENT_MASK;

  // 50% chance on a 0-127 range means checking if it's < 64.
  // This accurately reflects a 50% chance after the 0x7F mask.
  return maskedRng < RNG_50_PERCENT_THRESHOLD;
}

/**
 * Chooses a random caller uniformly from a pool of available callers.
 *
 * Gen 2 Caller Sampling (`ChooseRandomCaller`):
 * Uses `Random` along with `SimpleDivide` against `wNumAvailableCallers` to sample uniformly.
 *
 * @param availableCallers Array of contacts available at the current time.
 * @param randomByte A random byte generated by the RNG (0-255).
 * @returns The selected Contact, or null if no callers are available.
 */
export function chooseRandomCaller(availableCallers: Contact[], randomByte: number): Contact | null {
  if (!availableCallers || availableCallers.length === 0) {
    return null;
  }

  const numAvailable = availableCallers.length;

  // Gen 2 uses SimpleDivide, which is equivalent to modulo for picking an index.
  // randomByte % numAvailable
  const selectedIndex = randomByte % numAvailable;

  return availableCallers[selectedIndex] ?? null;
}
