// Module-level constants for bitmasks and RNG mechanics
export const RNG_50_PERCENT_MASK = 0b01111111;
export const RNG_50_PERCENT_THRESHOLD = 64;

/**
 * Timer Evaluation State
 */
export interface TimerState {
  delayMinsRemaining: number;
  timeCyclesSinceLastCall: number;
}

/**
 * Contact interface
 */
export interface Contact {
  id: number;
  name: string;
  isSwarm?: boolean;
  hasRareItem?: boolean;
  isHighValue?: boolean;
}

// Module-level constants for swarm and item flags
export const SWARM_FLAG_DUNSPARCE_BIT = 2;
export const SWARM_FLAG_YANMA_BIT = 3;

export const ITEM_FLAG_BEVERLY_BIT = 0;
export const ITEM_FLAG_JOSE_BIT = 1;
export const ITEM_FLAG_WADE_BIT = 2;
export const ITEM_FLAG_GINA_BIT = 3;
export const ITEM_FLAG_ALAN_BIT = 4;
export const ITEM_FLAG_LIZ_BIT = 5;
export const ITEM_FLAG_DEREK_BIT = 6;
export const ITEM_FLAG_TULLY_BIT = 7;
export const ITEM_FLAG_TIFFANY_BIT = 8;
export const ITEM_FLAG_WILTON_BIT = 9;

// Phone contact IDs
export const PHONE_CONTACT_BEVERLY = 6;
export const PHONE_CONTACT_JOSE = 13;
export const PHONE_CONTACT_WADE = 16;
export const PHONE_CONTACT_LIZ = 18;
export const PHONE_CONTACT_ANTHONY = 19;
export const PHONE_CONTACT_GINA = 21;
export const PHONE_CONTACT_ARNIE = 23;
export const PHONE_CONTACT_ALAN = 24;
export const PHONE_CONTACT_DEREK = 28;
export const PHONE_CONTACT_TULLY = 29;
export const PHONE_CONTACT_TIFFANY = 31;
export const PHONE_CONTACT_WILTON = 33;

/**
 * Checks if a phone call should trigger based on timer evaluation and a 50% RNG probability.
 *
 * @param timerState State representing the cooling-off period.
 * @param randomByte A random byte generated by the RNG (0-255).
 * @returns true if the phone call check passes, false otherwise.
 */
export function checkPhoneCall(timerState: TimerState, randomByte: number): boolean {
  if (timerState.delayMinsRemaining > 0) {
    return false;
  }
  const maskedRng = randomByte & RNG_50_PERCENT_MASK;
  return maskedRng < RNG_50_PERCENT_THRESHOLD;
}

/**
 * Chooses a random caller uniformly from a pool of available callers.
 *
 * @param availableCallers Array of contacts available at the current time.
 * @param randomByte A random byte generated by the RNG (0-255).
 * @returns The selected Contact, or null if no callers are available.
 */
export function chooseRandomCaller(availableCallers: Contact[], randomByte: number): Contact | null {
  if (!availableCallers || availableCallers.length === 0) {
    return null;
  }
  const selectedIndex = randomByte % availableCallers.length;
  return availableCallers[selectedIndex] ?? null;
}

/**
 * Enriches a contact with swarm and rare item flags based on game state.
 *
 * @param contact The contact to enrich.
 * @param swarmFlags The 1-byte wSwarmFlags value.
 * @param dailyItemFlags The 4-byte wDailyPhoneItemFlags value (as a 32-bit integer).
 * @returns The enriched contact.
 */
export function enrichContact(contact: Contact, swarmFlags: number, dailyItemFlags: number): Contact {
  let isSwarm = false;
  let hasRareItem = false;

  if (contact.id === PHONE_CONTACT_ANTHONY) {
    isSwarm = (swarmFlags & (1 << SWARM_FLAG_DUNSPARCE_BIT)) !== 0;
  } else if (contact.id === PHONE_CONTACT_ARNIE) {
    isSwarm = (swarmFlags & (1 << SWARM_FLAG_YANMA_BIT)) !== 0;
  }

  const checkItemFlag = (bit: number) => (dailyItemFlags & (1 << bit)) !== 0;

  switch (contact.id) {
    case PHONE_CONTACT_BEVERLY:
      hasRareItem = checkItemFlag(ITEM_FLAG_BEVERLY_BIT);
      break;
    case PHONE_CONTACT_JOSE:
      hasRareItem = checkItemFlag(ITEM_FLAG_JOSE_BIT);
      break;
    case PHONE_CONTACT_WADE:
      hasRareItem = checkItemFlag(ITEM_FLAG_WADE_BIT);
      break;
    case PHONE_CONTACT_GINA:
      hasRareItem = checkItemFlag(ITEM_FLAG_GINA_BIT);
      break;
    case PHONE_CONTACT_ALAN:
      hasRareItem = checkItemFlag(ITEM_FLAG_ALAN_BIT);
      break;
    case PHONE_CONTACT_LIZ:
      hasRareItem = checkItemFlag(ITEM_FLAG_LIZ_BIT);
      break;
    case PHONE_CONTACT_DEREK:
      hasRareItem = checkItemFlag(ITEM_FLAG_DEREK_BIT);
      break;
    case PHONE_CONTACT_TULLY:
      hasRareItem = checkItemFlag(ITEM_FLAG_TULLY_BIT);
      break;
    case PHONE_CONTACT_TIFFANY:
      hasRareItem = checkItemFlag(ITEM_FLAG_TIFFANY_BIT);
      break;
    case PHONE_CONTACT_WILTON:
      hasRareItem = checkItemFlag(ITEM_FLAG_WILTON_BIT);
      break;
  }

  const isHighValue = isSwarm || hasRareItem;

  return {
    ...contact,
    isSwarm,
    hasRareItem,
    isHighValue,
  };
}

/**
 * Filters a list of contacts to only include high-value callers.
 *
 * @param contacts Array of contacts.
 * @param swarmFlags The 1-byte wSwarmFlags value.
 * @param dailyItemFlags The 4-byte wDailyPhoneItemFlags value.
 * @returns Array of enriched, high-value contacts.
 */
export function filterHighValueCalls(contacts: Contact[], swarmFlags: number, dailyItemFlags: number): Contact[] {
  return contacts.map((c) => enrichContact(c, swarmFlags, dailyItemFlags)).filter((c) => c.isHighValue);
}
