export const ITEM_EON_TICKET = 0x0113;
export const ITEM_MYSTIC_TICKET = 0x0172;
export const ITEM_AURORA_TICKET = 0x0173;
export const ITEM_OLD_SEA_MAP = 0x0174;

export const KEY_ITEM_POCKET_OFFSET_RS = 0x05b0;
export const KEY_ITEM_POCKET_OFFSET_EMERALD = 0x05d8;
export const KEY_ITEM_POCKET_OFFSET_FRLG = 0x03b8;
export const KEY_ITEM_POCKET_SIZE_RS = 80;
export const KEY_ITEM_POCKET_SIZE_EMERALD = 120;
export const KEY_ITEM_POCKET_SIZE_FRLG = 120;

export const BERRY_POCKET_OFFSET_RS = 0x0740;
export const BERRY_POCKET_OFFSET_EMERALD = 0x0790;
export const BERRY_POCKET_OFFSET_FRLG = 0x054c;
export const BERRY_POCKET_SIZE_RS = 184;
export const BERRY_POCKET_SIZE_EMERALD = 184;
export const BERRY_POCKET_SIZE_FRLG = 172;

export const ITEM_INDEX_OFFSET = 0x00;
export const ITEM_ENTRY_SIZE = 4;
