// This file maps internal game IDs to standard names or PokeAPI slugs

export const GEN1_MAP_TO_SLUG: Record<number, string> = {
  0x00: 'pallet-town-area',
  0x01: 'viridian-city-area',
  0x02: 'pewter-city-area',
  0x03: 'cerulean-city-area',
  0x04: 'lavender-town-area',
  0x05: 'vermilion-city-area',
  0x06: 'celadon-city-area',
  0x07: 'fuchsia-city-area',
  0x08: 'cinnabar-island-area',
  0x0A: 'saffron-city-area',
  0x0C: 'route-1-area',
  0x0D: 'route-2-area',
  0x0E: 'route-3-area',
  0x0F: 'route-4-area',
  0x10: 'route-5-area',
  0x11: 'route-6-area',
  0x12: 'route-7-area',
  0x13: 'route-8-area',
  0x14: 'route-9-area',
  0x15: 'route-10-area',
  0x16: 'route-11-area',
  0x17: 'route-12-area',
  0x18: 'route-13-area',
  0x19: 'route-14-area',
  0x1A: 'route-15-area',
  0x1B: 'route-16-area',
  0x1C: 'route-17-area',
  0x1D: 'route-18-area',
  0x1E: 'route-19-area',
  0x1F: 'route-20-area',
  0x20: 'route-21-area',
  0x21: 'route-22-area',
  0x22: 'route-23-area',
  0x23: 'route-24-area',
  0x24: 'route-25-area',
  0x28: 'route-8-area', 
  0x5A: 'viridian-forest-area',
  0x5C: 'mt-moon-b1f', 
  0xCA: 'rock-tunnel-1f',
  0xC1: 'power-plant-area',
  0xD4: 'saffron-city-area', 
  0xD6: 'kanto-safari-zone-center',
  0xE2: 'cerulean-cave-1f',
};

export const GEN2_MAP_TO_SLUG: Record<number, Record<number, string>> = {
  3: { 
    1: 'new-bark-town-area',
    2: 'cherrygrove-city-area',
    3: 'violet-city-area',
    4: 'azalea-town-area',
    5: 'cianwood-city-area',
    6: 'goldenrod-city-area',
    7: 'olivine-city-area',
    8: 'ecruteak-city-area',
    9: 'mahogany-town-area',
    10: 'lake-of-rage-area',
    11: 'blackthorn-city-area',
  },
};

export const GEN1_ITEMS = {
  MOON_STONE: 0x0A,
  FIRE_STONE: 0x20,
  THUNDER_STONE: 0x21,
  WATER_STONE: 0x22,
  LEAF_STONE: 0x2F,
};

export const OBEDIENCE_CAPS = [
  { badges: 0, level: 10 },
  { badges: 2, level: 30 }, 
  { badges: 4, level: 50 }, 
  { badges: 6, level: 70 }, 
  { badges: 8, level: 100 }, 
];

export const STATIC_GIFT_DATA: Record<number, { name: string, location: string, reason: string }> = {
  131: { name: 'Lapras', location: 'Silph Co. 7F', reason: 'Gift from NPC during Silph Co. invasion' },
  133: { name: 'Eevee', location: 'Celadon Mansion', reason: 'Gift from the back entrance' },
  106: { name: 'Hitmonlee', location: 'Saffron Fighting Dojo', reason: 'Reward' },
  107: { name: 'Hitmonchan', location: 'Saffron Fighting Dojo', reason: 'Reward' },
  138: { name: 'Omanyte', location: 'Cinnabar Lab', reason: 'Fossil' },
  140: { name: 'Kabuto', location: 'Cinnabar Lab', reason: 'Fossil' },
  142: { name: 'Aerodactyl', location: 'Cinnabar Lab', reason: 'Fossil' },
  143: { name: 'Snorlax', location: 'Route 12 / 16', reason: 'Static' },
  144: { name: 'Articuno', location: 'Seafoam', reason: 'Static' },
  145: { name: 'Zapdos', location: 'Power Plant', reason: 'Static' },
  146: { name: 'Moltres', location: 'Victory Road', reason: 'Static' },
  150: { name: 'Mewtwo', location: 'Cerulean Cave', reason: 'Static' },
};
