export const missingPokemon: Record<string, number[]> = {
  red: [27, 28, 37, 38, 52, 53, 69, 70, 71, 126, 127],
  blue: [23, 24, 43, 44, 45, 56, 57, 58, 59, 123, 125],
  yellow: [13, 14, 15, 23, 24, 26, 52, 53, 109, 110, 124, 125, 126],
  gold: [13, 14, 15, 37, 38, 52, 53, 165, 166, 225, 227, 231, 232],
  silver: [10, 11, 12, 56, 57, 58, 59, 167, 168, 207, 216, 217, 226],
  crystal: [37, 38, 56, 57, 179, 180, 181, 203, 223, 224]
};

export const staticEncounters: Record<number, { red?: string[], blue?: string[], yellow?: string[], gold?: string[], silver?: string[], crystal?: string[] }> = {
  1: { red: ['Pallet Town (Starter)'], blue: ['Pallet Town (Starter)'], yellow: ['Cerulean City (Gift)'] },
  4: { red: ['Pallet Town (Starter)'], blue: ['Pallet Town (Starter)'], yellow: ['Route 24 (Gift)'] },
  7: { red: ['Pallet Town (Starter)'], blue: ['Pallet Town (Starter)'], yellow: ['Vermilion City (Gift)'] },
  25: { red: [], blue: [], yellow: ['Pallet Town (Starter)'] },
  29: { red: ['Route 5 (Trade for Nidoran♂)'], blue: ['Route 5 (Trade for Nidoran♂)'] },
  30: { red: ['Route 11 (Trade for Nidorino)'], blue: ['Route 11 (Trade for Nidorino)'] },
  32: { red: ['Route 5 (Trade for Nidoran♀)'], blue: ['Route 5 (Trade for Nidoran♀)'] },
  33: { red: ['Route 11 (Trade for Nidorina)'], blue: ['Route 11 (Trade for Nidorina)'] },
  35: { red: ['Celadon Game Corner'], blue: ['Celadon Game Corner'], yellow: ['Celadon Game Corner'] },
  37: { yellow: ['Celadon Game Corner'] },
  40: { yellow: ['Celadon Game Corner'] },
  63: { red: ['Celadon Game Corner'], blue: ['Celadon Game Corner'], yellow: ['Celadon Game Corner'] },
  66: { yellow: ['Route 5 (Trade for Cubone)'] },
  83: { red: ['Vermilion City (Trade for Spearow)'], blue: ['Vermilion City (Trade for Spearow)'] },
  86: { red: ['Cinnabar Island (Trade for Ponyta)'], blue: ['Cinnabar Island (Trade for Ponyta)'] },
  87: { yellow: ['Cinnabar Island (Trade for Growlithe)'] },
  89: { yellow: ['Cinnabar Island (Trade for Kangaskhan)'] },
  101: { red: ['Cinnabar Island (Trade for Raichu)'], blue: ['Cinnabar Island (Trade for Raichu)'] },
  108: { red: ['Route 18 (Trade for Slowbro)'], blue: ['Route 18 (Trade for Slowbro)'], yellow: ['Route 11 (Trade for Dugtrio)'] },
  112: { yellow: ['Cinnabar Island (Trade for Golduck)'] },
  114: { red: ['Cinnabar Island (Trade for Venonat)'], blue: ['Cinnabar Island (Trade for Venonat)'] },
  122: { red: ['Route 2 (Trade for Abra)'], blue: ['Route 2 (Trade for Abra)'], yellow: ['Route 2 (Trade for Clefairy)'] },
  123: { red: ['Celadon Game Corner'], yellow: ['Celadon Game Corner'] },
  124: { red: ['Cerulean City (Trade for Poliwhirl)'], blue: ['Cerulean City (Trade for Poliwhirl)'] },
  127: { blue: ['Celadon Game Corner'], yellow: ['Celadon Game Corner'] },
  129: { red: ['Route 4 PokeCenter (Buy for 500¥)'], blue: ['Route 4 PokeCenter (Buy for 500¥)'], yellow: ['Route 4 PokeCenter (Buy for 500¥)'] },
  131: { red: ['Silph Co. (Gift)'], blue: ['Silph Co. (Gift)'], yellow: ['Silph Co. (Gift)'], gold: ['Silph Co. (Trade)'], silver: ['Silph Co. (Trade)'], crystal: ['Silph Co. (Trade)'] },
  133: { red: ['Celadon Mansion (Gift)'], blue: ['Celadon Mansion (Gift)'], yellow: ['Celadon Mansion (Gift)'], gold: ['Goldenrod City (Gift)'], silver: ['Goldenrod City (Gift)'], crystal: ['Goldenrod City (Gift)'] },
  137: { red: ['Celadon Game Corner'], blue: ['Celadon Game Corner'], yellow: ['Celadon Game Corner'], gold: ['Celadon Game Corner'], silver: ['Celadon Game Corner'], crystal: ['Celadon Game Corner'] },
  138: { red: ['Mt. Moon (Helix Fossil)'], blue: ['Mt. Moon (Helix Fossil)'], yellow: ['Mt. Moon (Helix Fossil)'] },
  140: { red: ['Mt. Moon (Dome Fossil)'], blue: ['Mt. Moon (Dome Fossil)'], yellow: ['Mt. Moon (Dome Fossil)'] },
  142: { red: ['Pewter City (Old Amber)'], blue: ['Pewter City (Old Amber)'], yellow: ['Pewter City (Old Amber)'] },
  143: { red: ['Route 12 (Interact)', 'Route 16 (Interact)'], blue: ['Route 12 (Interact)', 'Route 16 (Interact)'], yellow: ['Route 12 (Interact)', 'Route 16 (Interact)'], gold: ['Vermilion City (Interact)'], silver: ['Vermilion City (Interact)'], crystal: ['Vermilion City (Interact)'] },
  144: { red: ['Seafoam Islands (Interact)'], blue: ['Seafoam Islands (Interact)'], yellow: ['Seafoam Islands (Interact)'] },
  145: { red: ['Power Plant (Interact)'], blue: ['Power Plant (Interact)'], yellow: ['Power Plant (Interact)'] },
  146: { red: ['Victory Road (Interact)'], blue: ['Victory Road (Interact)'], yellow: ['Victory Road (Interact)'] },
  147: { red: ['Celadon Game Corner'], blue: ['Celadon Game Corner'], yellow: ['Celadon Game Corner'], gold: ['Goldenrod Game Corner'], silver: ['Goldenrod Game Corner'], crystal: ['Goldenrod Game Corner'] },
  150: { red: ['Cerulean Cave (Interact)'], blue: ['Cerulean Cave (Interact)'], yellow: ['Cerulean Cave (Interact)'] },
  151: { red: ['Event / Glitch Only'], blue: ['Event / Glitch Only'], yellow: ['Event / Glitch Only'] },
  152: { gold: ['New Bark Town (Starter)'], silver: ['New Bark Town (Starter)'], crystal: ['New Bark Town (Starter)'] },
  155: { gold: ['New Bark Town (Starter)'], silver: ['New Bark Town (Starter)'], crystal: ['New Bark Town (Starter)'] },
  158: { gold: ['New Bark Town (Starter)'], silver: ['New Bark Town (Starter)'], crystal: ['New Bark Town (Starter)'] },
  175: { gold: ['Egg (Gift)'], silver: ['Egg (Gift)'], crystal: ['Egg (Gift)'] },
  185: { gold: ['Route 36 (Interact)'], silver: ['Route 36 (Interact)'], crystal: ['Route 36 (Interact)'] },
  213: { gold: ['Mt. Mortar (Gift)'], silver: ['Mt. Mortar (Gift)'], crystal: ['Mt. Mortar (Gift)'] },
  236: { gold: ['Mt. Mortar (Gift)'], silver: ['Mt. Mortar (Gift)'], crystal: ['Mt. Mortar (Gift)'] },
  243: { gold: ['Roam Johto'], silver: ['Roam Johto'], crystal: ['Roam Johto'] },
  244: { gold: ['Roam Johto'], silver: ['Roam Johto'], crystal: ['Roam Johto'] },
  245: { gold: ['Roam Johto'], silver: ['Roam Johto'], crystal: ['Roam Johto'] },
  249: { gold: ['Whirl Islands'], silver: ['Whirl Islands'], crystal: ['Whirl Islands'] },
  250: { gold: ['Tin Tower'], silver: ['Tin Tower'], crystal: ['Tin Tower'] },
  251: { gold: ['Event Only'], silver: ['Event Only'], crystal: ['Event Only'] },
};

export const stadiumRewardsData: Record<number, { stadium1?: string[], stadium2?: string[] }> = {
  25: { stadium1: ['Pika Cup / Round 2 (Surfing Pikachu)'] },
  54: { stadium1: ['Lickitung Cup (Amnesia Psyduck)'] },
  106: { stadium1: ['Beat Elite Four (Gift)'] }, // Hitmonlee
  107: { stadium1: ['Beat Elite Four (Gift)'] }, // Hitmonchan
  133: { stadium1: ['Beat Elite Four (Gift)'] }, // Eevee
  138: { stadium1: ['Beat Elite Four (Gift)'] }, // Omanyte
  140: { stadium1: ['Beat Elite Four (Gift)'] }, // Kabuto
  142: { stadium1: ['Beat Elite Four (Gift)'] }, // Aerodactyl
  147: { stadium1: ['Beat Elite Four (Gift)'] }, // Dratini
  
  // Stadium 2 (Gen 2)
  201: { stadium2: ['Beat Rival (Gift)'] }, // Unown (not really a gift, but interaction)
  175: { stadium2: ['Gift Egg (Togepi)'] },
  236: { stadium2: ['Gift Egg (Tyrogue)'] },
  172: { stadium2: ['Gift Egg (Pichu)'] },
  173: { stadium2: ['Gift Egg (Cleffa)'] },
  174: { stadium2: ['Gift Egg (Igglybuff)'] },
  238: { stadium2: ['Gift Egg (Smoochum)'] },
  239: { stadium2: ['Gift Egg (Elekid)'] },
  240: { stadium2: ['Gift Egg (Magby)'] },
  52: { stadium2: ['Trade for Hiker (Pay Day Meowth)'] }, 
};

export const stadiumRewardsSummary: Record<number, string> = {
  1: "Gym Leader Castle Reward",
  4: "Gym Leader Castle Reward",
  7: "Gym Leader Castle Reward",
  25: "Surfing Pikachu (Prime Cup Master Ball)",
  54: "Amnesia Psyduck (Hall of Fame)",
  106: "Gym Leader Castle Reward",
  107: "Gym Leader Castle Reward",
  133: "Gym Leader Castle Reward",
  138: "Gym Leader Castle Reward",
  140: "Gym Leader Castle Reward",
  207: "Earthquake Gligar (Round 2 Rival)",
};

export const gen2Items: Record<number, string> = {
  1: 'Master Ball', 2: 'Ultra Ball', 3: 'BrightPowder', 4: 'Great Ball', 5: 'Poké Ball',
  6: 'Teru-sama', 7: 'Bicycle', 8: 'Moon Stone', 9: 'Antidote', 10: 'Burn Heal',
  11: 'Ice Heal', 12: 'Awakening', 13: 'Parlyz Heal', 14: 'Full Restore', 15: 'Max Potion',
  16: 'Hyper Potion', 17: 'Super Potion', 18: 'Potion', 19: 'Escape Rope', 20: 'Repel',
  21: 'Max Elixer', 22: 'Fire Stone', 23: 'ThunderStone', 24: 'Water Stone', 25: 'Teru-sama',
  26: 'HP Up', 27: 'Protein', 28: 'Iron', 29: 'Carbos', 30: 'Lucky Punch',
  31: 'Calcium', 32: 'Rare Candy', 33: 'X Accuracy', 34: 'Leaf Stone', 35: 'Metal Powder',
  36: 'Nugget', 37: 'Poké Doll', 38: 'Full Heal', 39: 'Revive', 40: 'Max Revive',
  41: 'Guard Spec.', 42: 'Super Repel', 43: 'Max Repel', 44: 'Dire Hit', 45: 'Teru-sama',
  46: 'Fresh Water', 47: 'Soda Pop', 48: 'Lemonade', 49: 'X Attack', 50: 'X Defend',
  51: 'X Speed', 52: 'X Special', 53: 'Coin Case', 54: 'Itemfinder', 55: 'Teru-sama',
  56: 'Exp.Share', 57: 'Old Rod', 58: 'Good Rod', 59: 'Silver Leaf', 60: 'Super Rod',
  61: 'PP Up', 62: 'Ether', 63: 'Max Ether', 64: 'Elixer', 65: 'Red Scale',
  66: 'SecretPotion', 67: 'S.S. Ticket', 68: 'Mystery Egg', 69: 'Clear Bell', 70: 'Silver Wing',
  71: 'Moomoo Milk', 72: 'Quick Claw', 73: 'PsnCureBerry', 74: 'Gold Leaf', 75: 'Soft Sand',
  76: 'Sharp Beak', 77: 'PrzCureBerry', 78: 'Burnt Berry', 79: 'Ice Berry', 80: 'Poison Barb',
  81: 'King\'s Rock', 82: 'Bitter Berry', 83: 'Mint Berry', 84: 'Red Apricorn', 85: 'TinyMushroom',
  86: 'Big Mushroom', 87: 'SilverPowder', 88: 'Blu Apricorn', 89: 'Teru-sama', 90: 'Amulet Coin',
  91: 'Ylw Apricorn', 92: 'Grn Apricorn', 93: 'Cleanse Tag', 94: 'Mystic Water', 95: 'TwistedSpoon',
  96: 'Wht Apricorn', 97: 'Blackbelt', 98: 'Blk Apricorn', 99: 'Pnk Apricorn', 100: 'BlackGlasses',
  101: 'SlowpokeTail', 102: 'Pink Bow', 103: 'Stick', 104: 'Smoke Ball', 105: 'NeverMeltIce',
  106: 'Magnet', 107: 'MiracleBerry', 108: 'Pearl', 109: 'Big Pearl', 110: 'Everstone',
  111: 'Spell Tag', 112: 'RageCandyBar', 113: 'GS Ball', 114: 'Blue Card', 115: 'Miracle Seed',
  116: 'Thick Club', 117: 'Focus Band', 118: 'Teru-sama', 119: 'EnergyPowder', 120: 'Energy Root',
  121: 'Heal Powder', 122: 'Revival Herb', 123: 'Hard Stone', 124: 'Lucky Egg', 125: 'Card Key',
  126: 'Machine Part', 127: 'Egg Ticket', 128: 'Lost Item', 129: 'Stardust', 130: 'Star Piece',
  131: 'Basement Key', 132: 'Pass', 133: 'Teru-sama', 134: 'Teru-sama', 135: 'Teru-sama',
  136: 'Teru-sama', 137: 'Teru-sama', 138: 'Teru-sama', 139: 'Teru-sama', 140: 'Teru-sama',
  141: 'Teru-sama', 142: 'Teru-sama', 143: 'Charcoal', 144: 'Berry Juice', 145: 'Scope Lens',
  146: 'Teru-sama', 147: 'Teru-sama', 148: 'Metal Coat', 149: 'Dragon Fang', 150: 'Teru-sama',
  151: 'Leftovers', 152: 'Teru-sama', 153: 'Teru-sama', 154: 'Teru-sama', 155: 'MysteryBerry',
  156: 'Dragon Scale', 157: 'Berserk Gene', 158: 'Teru-sama', 159: 'Teru-sama', 160: 'Teru-sama',
  161: 'Teru-sama', 162: 'Teru-sama', 163: 'Sacred Ash', 164: 'Heavy Ball', 165: 'Flower Mail',
  166: 'Level Ball', 167: 'Lure Ball', 168: 'Fast Ball', 169: 'Teru-sama', 170: 'Light Ball',
  171: 'Friend Ball', 172: 'Moon Ball', 173: 'Love Ball', 174: 'Normal Box', 175: 'Gorgeous Box',
  176: 'Sun Stone', 177: 'Polkadot Bow', 178: 'Teru-sama', 179: 'Up-Grade', 180: 'Berry',
  181: 'Gold Berry', 182: 'SquirtBottle', 183: 'Teru-sama', 184: 'Park Ball', 185: 'Rainbow Wing',
  186: 'Teru-sama', 187: 'Brick Piece', 188: 'Surf Mail', 189: 'Litebluemail', 190: 'Portraitmail',
  191: 'Lovely Mail', 192: 'Eon Mail', 193: 'Morph Mail', 194: 'Bluesky Mail', 195: 'Music Mail',
  196: 'Mirage Mail', 197: 'Teru-sama', 198: 'Teru-sama', 199: 'Teru-sama', 200: 'Teru-sama',
  201: 'Teru-sama', 202: 'Teru-sama', 203: 'Teru-sama', 204: 'Teru-sama', 205: 'Teru-sama',
  206: 'Teru-sama', 207: 'Teru-sama', 208: 'Teru-sama', 209: 'Teru-sama', 210: 'Teru-sama',
  211: 'Teru-sama', 212: 'Teru-sama', 213: 'Teru-sama', 214: 'Teru-sama', 215: 'Teru-sama',
  216: 'Teru-sama', 217: 'Teru-sama', 218: 'Teru-sama', 219: 'Teru-sama', 220: 'Teru-sama',
  221: 'Teru-sama', 222: 'Teru-sama', 223: 'Teru-sama', 224: 'Teru-sama', 225: 'Teru-sama',
  226: 'Teru-sama', 227: 'Teru-sama', 228: 'Teru-sama', 229: 'Teru-sama', 230: 'Teru-sama',
  231: 'Teru-sama', 232: 'Teru-sama', 233: 'Teru-sama', 234: 'Teru-sama', 235: 'Teru-sama',
  236: 'Teru-sama', 237: 'Teru-sama', 238: 'Teru-sama', 239: 'Teru-sama', 240: 'Teru-sama',
  241: 'Teru-sama', 242: 'Teru-sama', 243: 'Teru-sama', 244: 'Teru-sama', 245: 'Teru-sama',
  246: 'Teru-sama', 247: 'Teru-sama', 248: 'Teru-sama', 249: 'Teru-sama', 250: 'Teru-sama',
  251: 'Teru-sama', 252: 'Teru-sama', 253: 'Teru-sama', 254: 'Teru-sama', 255: 'Teru-sama'
};

export const gen2Locations: Record<number, string> = {
  1: 'New Bark Town', 2: 'Route 29', 3: 'Cherrygrove City', 4: 'Route 30', 5: 'Route 31',
  6: 'Violet City', 7: 'Sprout Tower', 8: 'Route 32', 9: 'Union Cave', 10: 'Route 33',
  11: 'Azalea Town', 12: 'Slowpoke Well', 13: 'Ilex Forest', 14: 'Route 34', 15: 'Goldenrod City',
  16: 'Radio Tower', 17: 'Route 35', 18: 'National Park', 19: 'Route 36', 20: 'Route 37',
  21: 'Ecruteak City', 22: 'Tin Tower', 23: 'Burned Tower', 24: 'Route 38', 25: 'Route 39',
  26: 'Olivine City', 27: 'Lighthouse', 28: 'Battle Tower', 29: 'Route 40', 30: 'Whirl Islands',
  31: 'Route 41', 32: 'Cianwood City', 33: 'Route 42', 34: 'Mt. Mortar', 35: 'Route 43',
  36: 'Lake of Rage', 37: 'Route 44', 38: 'Ice Path', 39: 'Blackthorn City', 40: 'Dragon\'s Den',
  41: 'Route 45', 42: 'Dark Cave', 43: 'Route 46', 44: 'Silver Cave', 45: 'Pallet Town',
  46: 'Route 1', 47: 'Viridian City', 48: 'Route 2', 49: 'Pewter City', 50: 'Route 3',
  51: 'Mt. Moon', 52: 'Route 4', 53: 'Cerulean City', 54: 'Route 24', 55: 'Route 25',
  56: 'Route 5', 57: 'Underground', 58: 'Route 6', 59: 'Vermilion City', 60: 'Diglett\'s Cave',
  61: 'Route 7', 62: 'Route 8', 63: 'Route 9', 64: 'Rock Tunnel', 65: 'Route 10',
  66: 'Lavender Town', 67: 'Pokémon Tower', 68: 'Route 11', 69: 'Route 12', 70: 'Route 13',
  71: 'Route 14', 72: 'Route 15', 73: 'Route 16', 74: 'Route 17', 75: 'Route 18',
  76: 'Fuchsia City', 77: 'Safari Zone', 78: 'Route 19', 79: 'Route 20', 80: 'Seafoam Islands',
  81: 'Route 21', 82: 'Cinnabar Island', 83: 'Route 22', 84: 'Route 23', 85: 'Victory Road',
  86: 'Route 26', 87: 'Route 27', 88: 'Tohjo Falls', 89: 'Route 28', 90: 'Fast Ship',
};
