// Mix Record offsets per Section 13 guidelines (module-level constants, no magic numbers)
export const MIXED_RECORD_NPC_LENGTH = 160;

export const MIXED_RECORD_NPC_TRAINER_NAME_OFFSET = 0x02;
export const MIXED_RECORD_NPC_TRAINER_NAME_LENGTH = 7;

export const MIXED_RECORD_NPC_TRAINER_GENDER_OFFSET = 0x07;
export const MIXED_RECORD_NPC_TRAINER_ID_OFFSET = 0x09;

export const MIXED_RECORD_NPC_PARTY_OFFSET = 0x34;
export const MIXED_RECORD_NPC_PARTY_COUNT = 6;

export const MIXED_RECORD_POKEMON_PERSONALITY_OFFSET = 0x00;
export const MIXED_RECORD_POKEMON_MOVES_OFFSET = 0x18;
export const MIXED_RECORD_POKEMON_SPECIES_OFFSET = 0x48;
export const MIXED_RECORD_POKEMON_HELD_ITEM_OFFSET = 0x54;
export const MIXED_RECORD_POKEMON_LEVEL_OFFSET = 0x60;
export const MIXED_RECORD_POKEMON_EVS_OFFSET = 0x66;

export const MIXED_RECORD_POKEMON_MOVES_COUNT = 4;
export const MIXED_RECORD_POKEMON_MOVE_SIZE = 2;
export const MIXED_RECORD_POKEMON_PERSONALITY_SIZE = 4;
export const MIXED_RECORD_POKEMON_SPECIES_SIZE = 2;
export const MIXED_RECORD_POKEMON_HELD_ITEM_SIZE = 2;
export const MIXED_RECORD_POKEMON_LEVEL_SIZE = 1;
export const MIXED_RECORD_POKEMON_EVS_SIZE = 1;

export const MIXED_RECORD_EMPTY_PERSONALITY_0 = 0;
export const MIXED_RECORD_EMPTY_PERSONALITY_FF = 0xffffffff;
