/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BoxAnalyzerRouteImport } from './routes/box-analyzer'
import { Route as DagRouteImport } from './routes/dag'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmulatorRouteImport } from './routes/emulator'
import { Route as SafariZoneRouteImport } from './routes/safari-zone'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as PokemonPokemonIdRouteImport } from './routes/pokemon.$pokemonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxAnalyzerRoute = BoxAnalyzerRouteImport.update({
  id: '/box-analyzer',
  path: '/box-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const DagRoute = DagRouteImport.update({
  id: '/dag',
  path: '/dag',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmulatorRoute = EmulatorRouteImport.update({
  id: '/emulator',
  path: '/emulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SafariZoneRoute = SafariZoneRouteImport.update({
  id: '/safari-zone',
  path: '/safari-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonIdRoute = PokemonPokemonIdRouteImport.update({
  id: '/pokemon/$pokemonId',
  path: '/pokemon/$pokemonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/box-analyzer': typeof BoxAnalyzerRoute
  '/dag': typeof DagRoute
  '/dashboard': typeof DashboardRoute
  '/emulator': typeof EmulatorRoute
  '/safari-zone': typeof SafariZoneRoute
  '/storage': typeof StorageRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/box-analyzer': typeof BoxAnalyzerRoute
  '/dag': typeof DagRoute
  '/dashboard': typeof DashboardRoute
  '/emulator': typeof EmulatorRoute
  '/safari-zone': typeof SafariZoneRoute
  '/storage': typeof StorageRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/box-analyzer': typeof BoxAnalyzerRoute
  '/dag': typeof DagRoute
  '/dashboard': typeof DashboardRoute
  '/emulator': typeof EmulatorRoute
  '/safari-zone': typeof SafariZoneRoute
  '/storage': typeof StorageRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/box-analyzer'
    | '/dag'
    | '/dashboard'
    | '/emulator'
    | '/safari-zone'
    | '/storage'
    | '/pokemon/$pokemonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/box-analyzer'
    | '/dag'
    | '/dashboard'
    | '/emulator'
    | '/safari-zone'
    | '/storage'
    | '/pokemon/$pokemonId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/box-analyzer'
    | '/dag'
    | '/dashboard'
    | '/emulator'
    | '/safari-zone'
    | '/storage'
    | '/pokemon/$pokemonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BoxAnalyzerRoute: typeof BoxAnalyzerRoute
  DagRoute: typeof DagRoute
  DashboardRoute: typeof DashboardRoute
  EmulatorRoute: typeof EmulatorRoute
  SafariZoneRoute: typeof SafariZoneRoute
  StorageRoute: typeof StorageRoute
  PokemonPokemonIdRoute: typeof PokemonPokemonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-analyzer': {
      id: '/box-analyzer'
      path: '/box-analyzer'
      fullPath: '/box-analyzer'
      preLoaderRoute: typeof BoxAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dag': {
      id: '/dag'
      path: '/dag'
      fullPath: '/dag'
      preLoaderRoute: typeof DagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emulator': {
      id: '/emulator'
      path: '/emulator'
      fullPath: '/emulator'
      preLoaderRoute: typeof EmulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safari-zone': {
      id: '/safari-zone'
      path: '/safari-zone'
      fullPath: '/safari-zone'
      preLoaderRoute: typeof SafariZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemonId': {
      id: '/pokemon/$pokemonId'
      path: '/pokemon/$pokemonId'
      fullPath: '/pokemon/$pokemonId'
      preLoaderRoute: typeof PokemonPokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BoxAnalyzerRoute: BoxAnalyzerRoute,
  DagRoute: DagRoute,
  DashboardRoute: DashboardRoute,
  EmulatorRoute: EmulatorRoute,
  SafariZoneRoute: SafariZoneRoute,
  StorageRoute: StorageRoute,
  PokemonPokemonIdRoute: PokemonPokemonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
