// @biome-ignore all: auto-generated file
/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AssistantRouteImport } from './routes/assistant';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PokemonPokemonIdRouteImport } from './routes/pokemon.$pokemonId';
import { Route as StorageRouteImport } from './routes/storage';

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any);
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PokemonPokemonIdRoute = PokemonPokemonIdRouteImport.update({
  id: '/pokemon/$pokemonId',
  path: '/pokemon/$pokemonId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/assistant': typeof AssistantRoute;
  '/storage': typeof StorageRoute;
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/assistant': typeof AssistantRoute;
  '/storage': typeof StorageRoute;
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/assistant': typeof AssistantRoute;
  '/storage': typeof StorageRoute;
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/assistant' | '/storage' | '/pokemon/$pokemonId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/assistant' | '/storage' | '/pokemon/$pokemonId';
  id: '__root__' | '/' | '/assistant' | '/storage' | '/pokemon/$pokemonId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AssistantRoute: typeof AssistantRoute;
  StorageRoute: typeof StorageRoute;
  PokemonPokemonIdRoute: typeof PokemonPokemonIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage';
      path: '/storage';
      fullPath: '/storage';
      preLoaderRoute: typeof StorageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/assistant': {
      id: '/assistant';
      path: '/assistant';
      fullPath: '/assistant';
      preLoaderRoute: typeof AssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pokemon/$pokemonId': {
      id: '/pokemon/$pokemonId';
      path: '/pokemon/$pokemonId';
      fullPath: '/pokemon/$pokemonId';
      preLoaderRoute: typeof PokemonPokemonIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  StorageRoute: StorageRoute,
  PokemonPokemonIdRoute: PokemonPokemonIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
