name: Playwright Tests
permissions:
  contents: read
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    name: "End-to-End Tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright E2E tests
      run: npm run test:e2e
      env:
        ARGOS_BUILD_NAME: "E2E"
        ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-e2e-report
        path: playwright-report/
        retention-days: 30
    - name: Argos upload
      if: always()
      run: npx argos upload ./screenshots --token ${{ secrets.ARGOS_TOKEN }}
