name: Playwright Tests
permissions:
  contents: read
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    name: "End-to-End Tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ 'Desktop FullHD', 'Desktop 1440p', 'Mobile Pixel 9' ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright E2E tests
      run: npx playwright test --project="${{ matrix.project }}"
      env:
        ARGOS_BUILD_NAME: "E2E ${{ matrix.project }}"
        ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-e2e-report-${{ matrix.project }}
        path: playwright-report/
        retention-days: 30

  ct:
    name: "Component Tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ 'Desktop FullHD', 'Desktop 1440p', 'Mobile Pixel 9' ]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright CT tests
      run: npx playwright test -c playwright-ct.config.ts --project="${{ matrix.project }}"
      env:
        ARGOS_BUILD_NAME: "Component ${{ matrix.project }}"
        ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-ct-report-${{ matrix.project }}
        path: playwright-report/
        retention-days: 30
